In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
tf.__version__

'2.18.0'

In [3]:
path_to_file = '/content/shakespeare (1).txt'

In [4]:
text = open(path_to_file, 'r').read()

In [5]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [6]:
# The unique characters in the file
vocab = sorted(set(text))
print(vocab)
len(vocab)

['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|']


82

In [7]:
char_to_ind = {u:i for i, u in enumerate(vocab)}

In [8]:
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 'a': 55,
 'b': 56,
 'c': 57,
 'd': 58,
 'e': 59,
 'f': 60,
 'g': 61,
 'h': 62,
 'i': 63,
 'j': 64,
 'k': 65,
 'l': 66,
 'm': 67,
 'n': 68,
 'o': 69,
 'p': 70,
 'q': 71,
 'r': 72,
 's': 73,
 't': 74,
 'u': 75,
 'v': 76,
 'w': 77,
 'x': 78,
 'y': 79,
 'z': 80,
 '|': 81}

In [9]:
ind_to_char = np.array(vocab)

In [10]:
ind_to_char

array(['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1',
       '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?',
       'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j',
       'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w',
       'x', 'y', 'z', '|'], dtype='<U1')

In [11]:
encoded_text = np.array([char_to_ind[c] for c in text])

In [12]:
encoded_text

array([ 0,  1,  1, ..., 50, 59, 73])

In [13]:
sample = text[:20]
sample

'\n                   '

In [14]:
encoded_text[:20]

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [16]:
line = "From fairest creatures we desire increase"

In [17]:
len(line)

41

In [18]:
part_stanza = """From fairest creatures we desire increase,
That thereby beauty's rose might never die,
But as the riper should by time decease,"""

In [19]:
len(part_stanza)

127

In [20]:
seq_len = 120

In [21]:
total_num_seq = len(text)//(seq_len+1)

In [22]:
total_num_seq

8665

In [23]:
# Create Training Sequences
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)
for i in char_dataset.take(500):

   print(ind_to_char[i.numpy()])



 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
1


 
 
F
r
o
m
 
f
a
i
r
e
s
t
 
c
r
e
a
t
u
r
e
s
 
w
e
 
d
e
s
i
r
e
 
i
n
c
r
e
a
s
e
,


 
 
T
h
a
t
 
t
h
e
r
e
b
y
 
b
e
a
u
t
y
'
s
 
r
o
s
e
 
m
i
g
h
t
 
n
e
v
e
r
 
d
i
e
,


 
 
B
u
t
 
a
s
 
t
h
e
 
r
i
p
e
r
 
s
h
o
u
l
d
 
b
y
 
t
i
m
e
 
d
e
c
e
a
s
e
,


 
 
H
i
s
 
t
e
n
d
e
r
 
h
e
i
r
 
m
i
g
h
t
 
b
e
a
r
 
h
i
s
 
m
e
m
o
r
y
:


 
 
B
u
t
 
t
h
o
u
 
c
o
n
t
r
a
c
t
e
d
 
t
o
 
t
h
i
n
e
 
o
w
n
 
b
r
i
g
h
t
 
e
y
e
s
,


 
 
F
e
e
d
'
s
t
 
t
h
y
 
l
i
g
h
t
'
s
 
f
l
a
m
e
 
w
i
t
h
 
s
e
l
f
-
s
u
b
s
t
a
n
t
i
a
l
 
f
u
e
l
,


 
 
M
a
k
i
n
g
 
a
 
f
a
m
i
n
e
 
w
h
e
r
e
 
a
b
u
n
d
a
n
c
e
 
l
i
e
s
,


 
 
T
h
y
 
s
e
l
f
 
t
h
y
 
f
o
e
,
 
t
o
 
t
h
y
 
s
w
e
e
t
 
s
e
l
f
 
t
o
o
 
c
r
u
e
l
:


 
 
T
h
o
u
 
t
h
a
t
 
a
r
t
 
n
o
w
 
t
h
e
 
w
o
r
l
d
'
s
 
f
r
e
s
h
 
o
r
n
a
m
e
n
t
,


 
 
A
n
d
 
o
n
l
y
 
h
e
r
a
l
d
 
t
o
 
t
h
e
 
g
a
u
d
y
 
s
p
r
i
n
g
,


 
 
W
i
t
h
i
n
 
t
h
i
n
e
 
o
w
n
 
b
u


In [24]:
sequences = char_dataset.batch(seq_len+1, drop_remainder=True)

In [25]:
def create_seq_targets(seq):
    input_txt = seq[:-1]
    target_txt = seq[1:]
    return input_txt, target_txt

In [26]:
dataset = sequences.map(create_seq_targets)

In [27]:
for input_txt, target_txt in dataset.take(1):
    print(input_txt.numpy())
    print(''.join(ind_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
# There is an extra whitespace!
    print(''.join(ind_to_char[target_txt.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 72 69 67  1 60 55 63 72 59 73 74  1 57 72 59 55 74 75 72 59 73
  1 77 59  1 58 59 73 63 72 59  1 63 68 57 72 59 55 73 59  8  0  1  1 45
 62 55 74  1 74 62 59 72 59 56 79  1 56 59 55 75 74 79  5 73  1 72 69 73
 59  1 67 63 61 62 74  1 68 59 76 59 72  1 58 63 59  8  0  1  1 27 75 74]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 72 69 67  1 60 55 63 72 59 73 74  1 57 72 59 55 74 75 72 59 73  1
 77 59  1 58 59 73 63 72 59  1 63 68 57 72 59 55 73 59  8  0  1  1 45 62
 55 74  1 74 62 59 72 59 56 79  1 56 59 55 75 74 79  5 73  1 72 69 73 59
  1 67 63 61 62 74  1 68 59 76 59 72  1 58 63 59  8  0  1  1 27 75 74  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [28]:
# Batch size
batch_size = 128
# Buffer size to shuffle the dataset so it doesn't attempt to shuffle
# the entire sequence in memory. Instead, it maintains a buffer in which it shuffles el
buffer_size = 10000
dataset = dataset.shuffle(buffer_size).batch(batch_size, drop_remainder=True)

In [29]:
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(128, 120), dtype=tf.int64, name=None), TensorSpec(shape=(128, 120), dtype=tf.int64, name=None))>

In [30]:
# Length of the vocabulary in chars
vocab_size = len(vocab)
# The embedding dimension
embed_dim = 64
# Number of RNN units
rnn_neurons = 1026

In [31]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense,Embedding,Dropout,GRU

In [32]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [33]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module keras.src.losses.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, ignore_class=None, axis=-1)
    Computes the sparse categorical crossentropy loss.
    
    Args:
        y_true: Ground truth values.
        y_pred: The predicted values.
        from_logits: Whether `y_pred` is expected to be a logits tensor. By
            default, we assume that `y_pred` encodes a probability distribution.
        ignore_class: Optional integer. The ID of a class to be ignored during
            loss computation. This is useful, for example, in segmentation
            problems featuring a "void" class (commonly -1 or 255) in
            segmentation maps. By default (`ignore_class=None`), all classes are
            considered.
        axis: Defaults to `-1`. The dimension along which the entropy is
            computed.
    
    Returns:
        Sparse categorical crossentropy loss value.
    
    Examples:
    


In [34]:
def sparse_cat_loss(y_true, y_pred):
    return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)


In [35]:
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model

def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    # Define Input layer with batch size for stateful RNN
    inputs = Input(batch_shape=(batch_size, None), name="input_layer")

    x = Embedding(input_dim=vocab_size, output_dim=embed_dim)(inputs)
    x = GRU(rnn_neurons,
            return_sequences=True,
            stateful=True,
            recurrent_initializer='glorot_uniform')(x)
    outputs = Dense(vocab_size)(x)

    model = Model(inputs, outputs)
    model.compile(optimizer='adam', loss=sparse_cat_loss)
    return model

In [36]:
model = create_model(
vocab_size = vocab_size,
embed_dim = embed_dim,
rnn_neurons = rnn_neurons,
batch_size = batch_size)

In [37]:
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)             │ (128, None)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ embedding (Embedding)                │ (128, None, 64)             │           5,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ gru (GRU)                            │ (128, None, 1026)           │       3,361,176 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (128, None, 82)             │          84,214 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,450,638 (13.16 MB)

 Trainable params: 3,450,638 (13.16 MB)

 Non-trainable params: 0 (0.00 B)

In [38]:
for input_example_batch, target_example_batch in dataset.take(1):
    example_batch_predictions = model(input_example_batch)
    print(example_batch_predictions.shape, "<=== (batch_size, sequence_length, vocab_size)")


(128, 120, 82) <=== (batch_size, sequence_length, vocab_size)


In [39]:
example_batch_predictions

<tf.Tensor: shape=(128, 120, 82), dtype=float32, numpy=
array([[[ 4.39414661e-03, -5.69357583e-03, -4.50037373e-03, ...,
         -3.82557139e-03, -1.10844627e-03, -4.63541970e-03],
        [ 2.18575262e-03, -3.52036091e-03, -5.67104714e-03, ...,
          1.73152337e-04,  1.84504618e-03,  1.41693873e-03],
        [-4.82340483e-03, -8.51976313e-03, -3.07584531e-03, ...,
         -3.54486139e-04,  6.66978827e-04,  7.53199495e-03],
        ...,
        [ 5.70557266e-03, -1.45323121e-03,  1.34303560e-03, ...,
          4.80644358e-03,  2.27917032e-03,  6.02803193e-03],
        [ 8.18385184e-03,  1.32051413e-04, -2.56036175e-04, ...,
          6.14866847e-03, -4.69826581e-03,  3.64655745e-03],
        [ 3.07647558e-03, -4.43212979e-04,  2.19128910e-03, ...,
          2.15693470e-03, -5.18550910e-03, -1.94367405e-03]],

       [[ 5.01759676e-03,  3.68522742e-04, -4.83711949e-04, ...,
          4.94126556e-03, -5.85314957e-03,  1.07577897e-03],
        [-6.55132998e-03,  7.94780441e-03,  8.5

In [40]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)

In [41]:
sampled_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[33],
       [60],
       [24],
       [52],
       [41],
       [28],
       [26],
       [38],
       [73],
       [36],
       [81],
       [29],
       [55],
       [ 1],
       [63],
       [62],
       [40],
       [53],
       [66],
       [45],
       [38],
       [15],
       [24],
       [49],
       [53],
       [40],
       [ 4],
       [14],
       [73],
       [71],
       [65],
       [36],
       [69],
       [52],
       [79],
       [ 9],
       [45],
       [75],
       [22],
       [34],
       [75],
       [ 9],
       [39],
       [34],
       [22],
       [39],
       [37],
       [56],
       [79],
       [47],
       [10],
       [70],
       [67],
       [ 5],
       [31],
       [41],
       [67],
       [ 2],
       [18],
       [40],
       [65],
       [50],
       [70],
       [23],
       [ 7],
       [47],
       [60],
       [59],
       [77],
       [ 1],
       [ 1],
       [35],
       [26],
   

In [42]:
 #Reformat to not be a lists of lists
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()

In [43]:
sampled_indices

array([33, 60, 24, 52, 41, 28, 26, 38, 73, 36, 81, 29, 55,  1, 63, 62, 40,
       53, 66, 45, 38, 15, 24, 49, 53, 40,  4, 14, 73, 71, 65, 36, 69, 52,
       79,  9, 45, 75, 22, 34, 75,  9, 39, 34, 22, 39, 37, 56, 79, 47, 10,
       70, 67,  5, 31, 41, 67,  2, 18, 40, 65, 50, 70, 23,  7, 47, 60, 59,
       77,  1,  1, 35, 26, 77, 53, 19, 51, 49, 70, 58, 75, 13, 81, 42, 59,
       74, 46, 41, 77, 60, 67, 77, 37, 67,  3, 29, 80, 22, 27, 57, 37, 49,
       22, 36, 53, 40, 73, 50, 55, 76, 60, 61, 59, 51, 73, 36, 49, 58, 35,
       81])

In [44]:
print("Given the input seq: \n")
print("".join(ind_to_char[input_example_batch[0]]))
print('\n')
print("Next Char Predictions: \n")
print("".join(ind_to_char[sampled_indices ]))

Given the input seq: 

uy
    my fortunes.
  OLIVER. And what wilt thou do? Beg, when that is spent? Well, sir,
    get you in. I will not long


Next Char Predictions: 

Hf>[PCAMsK|Da ihO]lTM4>X]O&3sqkKo[y-Tu;Iu-NI;NLbyV.pm'FPm!7OkYp<)Vfew  JAw]8ZXpdu2|QetUPwfmwLm"Dz;BcLX;K]OsYavfgeZsKXdJ|


In [45]:
epochs = 30

In [46]:
model.fit(dataset,epochs=epochs)

Epoch 1/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 13s 133ms/step - loss: 3.9071
Epoch 2/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 11s 137ms/step - loss: 2.4007
Epoch 3/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 11s 141ms/step - loss: 2.0973
Epoch 4/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 12s 145ms/step - loss: 1.9199
Epoch 5/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 12s 152ms/step - loss: 1.7755
Epoch 6/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 12s 151ms/step - loss: 1.6522
Epoch 7/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 11s 144ms/step - loss: 1.5601
Epoch 8/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 20s 139ms/step - loss: 1.4865
Epoch 9/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 11s 144ms/step - loss: 1.4344
Epoch 10/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 12s 151ms/step - loss: 1.3832
Epoch 11/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 12s 157ms/step - loss: 1.3475
Epoch 12/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 12s 148ms/step - loss: 1.3120
Epoch 13/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 21s 139ms/step - loss: 1.2849
Epoch 14/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 12s 142ms/step - loss: 1.2581
Epoch 15/30
67/67 ━━━━━━━━━━━━━━━━━━━━ 13s 

In [47]:
model.save('shakespeare_gen.h5')

In [48]:
from tensorflow.keras.models import load_model

In [49]:
model = create_model(vocab_size, embed_dim, rnn_neurons, batch_size=1)

In [50]:
model.load_weights('shakespeare_gen.h5')

In [51]:
model.build(tf.TensorShape([1, None]))

In [52]:
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)             │ (1, None)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ embedding_1 (Embedding)              │ (1, None, 64)               │           5,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ gru_1 (GRU)                          │ (1, None, 1026)             │       3,361,176 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (1, None, 82)               │          84,214 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,450,638 (13.16 MB)

 Trainable params: 3,450,638 (13.16 MB)

 Non-trainable params: 0 (0.00 B)

In [56]:
def generate_text(model, start_seed,gen_size=100,temp=1.0):
    '''
    model: Trained Model to Generate Text
    start_seed: Intial Seed text in string form
    gen_size: Number of characters to generate
    Basic idea behind this function is to take in some seed text, format it so
    that it is in the correct shape for our network, then loop the sequence as
    we keep adding our own predicted characters. Similar to our work in the RNN
    time series problems.
    '''
    # Number of characters to generate
    num_generate = gen_size
    # Vecotrizing starting seed text
    input_eval = [char_to_ind[s] for s in start_seed]
    # Expand to match batch format shape
    input_eval = tf.expand_dims(input_eval, 0)
    # Empty list to hold resulting generated text
    text_generated = []
    # Temperature effects randomness in our resulting text
    # The term is derived from entropy/thermodynamics.
    # The temperature is used to effect probability of next characters.
    # Higher probability == lesss surprising/ more expected
    # Lower temperature == more surprising / less expected
    temperature = temp
    # Here batch size == 1
    # model.reset_states() # Remove this line to solve the problem! The Functional model does not have reset_states attribute
    for i in range(num_generate):
        # Generate Predictions
        predictions = model(input_eval)
        # Remove the batch shape dimension
        predictions = tf.squeeze(predictions, 0)
        # Use a cateogircal disitribution to select the next character
        predictions = predictions / temperature
        predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()
        # Pass the predicted charracter for the next input
        input_eval = tf.expand_dims([predicted_id], 0)
        # Transform back to character letter
        text_generated.append(ind_to_char[predicted_id])
    return (start_seed + ''.join(text_generated))

In [57]:
print(generate_text(model,"flower",gen_size=1000))

flowers a wife?
  SILVIUS. I have one that speak of bites shoothen,
    Which more than such followers a crossation
    To ask 'gainst Princess.                       fold scarf as such
    fellow, and would undont them-us, and never come hither;
    And in that rade of faults I will Ture black'd, I know not whose bat for me; event
    O the world knight thy dead with that shall be stol'n up.
    I'll make an endman dirch we call be worth for Gilenum.
    Fine to his figures for here above this head,
    As if covering in rats that he is. Most now.
  Mar. And in time to hangman that her woes Will you
     mather but a minute bond and your firestin?
  Readnest near he has no other might blow a sea-'t, AEDILE
US. Fare thee hen? Rangain, well be answer'd with another boy
                  'twas a conqueror familiar than liv'd
    Baster, your helms will lature me farting for made:  
    But what noirs you for love, I love more fruit.
  FIRST SERVANT. But do not fled well for Rome. As I'll